# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180828_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qty',
            field=models.IntegerField(default=30),
        ),
    ]
